#!/usr/bin/env node

const fetch = require('isomorphic-unfetch')
const promisify = require('util').promisify
const writeFile = promisify(require('fs').writeFile)

process.on('unhandledRejection', (err) => {
  console.error('Unhandled Rejection', err)
  process.exit(1)
})

async function getData () {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts?_page=1')
  return response.json()
}

async function writeToDisk (posts, path) {
  writeFile(path, JSON.stringify(posts, null, 2))
}

getData()
  .then(p => writeToDisk(p, 'data.json'))
  .then(() => {console.log('Done')})
