#!/bin/bash -e

cd out
git init
git add .
git commit -m "Deploy to GitHub Pages"
git push --force --quiet "https://${GITHUB_TOKEN}@github.com/gaggle/repo-lister" master:gh-pages > /dev/null 2>&1 | echo "Deploying..."
echo "Site deployed"
