#!/bin/bash -e

OUTPUT_FOLDER=${1:-out}  # Default to 'out' folder

(PATH=$(npm bin):$PATH next export -o ${OUTPUT_FOLDER}) & A=$!
(PATH=$(npm bin):$PATH build-storybook -o ${OUTPUT_FOLDER}/storybook) & B=$1

wait ${A} && wait ${B}
exit_code=$?
if [[ ${exit_code} != 0 ]]; then exit ${exit_code}; fi

touch ${OUTPUT_FOLDER}/.nojekyll

echo list.jonlauridsen.com > ${OUTPUT_FOLDER}/CNAME

cp ./data.json ${OUTPUT_FOLDER}

mkdir -p ${OUTPUT_FOLDER}/fonts
cp ./node_modules/ionicons/dist/fonts/* ${OUTPUT_FOLDER}/fonts/
