#!/bin/bash -e

OUTPUT_FOLDER=${1:-out}  # Default to 'out' folder

PATH=$(npm bin):$PATH next export -o ${OUTPUT_FOLDER}

touch ${OUTPUT_FOLDER}/.nojekyll

echo list.jonlauridsen.com > ${OUTPUT_FOLDER}/CNAME

mkdir -p ${OUTPUT_FOLDER}/fonts/ionicons
cp ./node_modules/ionicons/dist/fonts/* ${OUTPUT_FOLDER}/fonts/ionicons/
