#!/bin/bash -euv

ORIG_CWD=$PWD
TMP="/tmp/repo-lister-external-usage/"

rm -rf ${TMP}/node_modules/repo-lister ${TMP}/node_modules/bin/repo-web ${TMP}/cache ${TMP}/out
mkdir -p ${TMP}/node_modules
cd ${TMP}

rsync -a ${ORIG_CWD}/tests/fixtures/sample-data/ scraped/

rm -f *.tgz
npm pack ${ORIG_CWD}
FILENAME=`ls *.tgz`

if [ ! -f package.json ]; then
    npm init --force
fi

npm install ${FILENAME} --save

mkdir out # CLI would crash if folder already existed and had files, so, we explicitly test for that case here
touch out/index.html

echo ${PWD}
PATH=$(npm bin):$PATH repo-web -d=data.json -s=static/ -o=out/ -c=cache/ --production
